phrase:
  project_id: ccca5d2028e8345d6f593706aec5ab8b
  push:
    sources:
      - file: ./frontend/lang/en-GB.json
        params:
          update_translations: true
          file_format: react_intl
          locale_id: 808cf1408742c54b2899e965b51519eb

  pull:
    targets:
      - file: ./frontend/lang/fr-fr.json
        params:
          file_format: react_intl
          locale_id: e969e624cf03d0742a13bc1a1a919802

