phrase:
  project_id: 2ef66a6e081b97950f24f8d83da110d5
  access_token: token_here

  push:
    sources:
      - file: ./frontend/lang/en-GB.json
        params:
          file_format: simple_json
          locale_id: cad77f9025d5f8f2da449706b4756b36
          autotranslate: true

  pull:
    targets:
      - file: ./frontend/lang/fr-CA.json
        params:
          file_format: simple_json
          locale_id: 85f94a70c376cbd8433a499efe3cb1d0

