phrase:
  project_id: a97f8a086fee56f9a4a8514205dc570e
  access_token: token_here

  push:
    sources:
      - file: ./frontend/lang/en-GB.json
        params:
          file_format: json
          locale_id: abfc3b0abd4e58606f72fb9bbf4422e7
          auto_translate: true

  pull:
    targets:
      - file: ./frontend/lang/fr-CA.json
        params:
          file_format: json
          locale_id: 6fad8fec3d2ffacc95143fc70d9467a7

